package oaiapi

import (
	"bytes"
	"encoding/json"
	"io"
	"net/http"
	"net/url"
)

var (
	PromptKindString        = "string"
	PromptKindStringArray   = "arrayofstrings"
	PromptKindTokenArray    = "arrayoftokens"
	PromptKindArrayOfTokens = "arrayoftokenarrays"
)

type Token string

type PromptType struct {
	Kind          string
	StringValue   string
	StringArray   []string
	TokenArray    []Token
	ArrayOfTokens [][]Token
}

// CompletionReq represents a request to the chat completion API.
// Refer to https://platform.openai.com/docs/api-reference/completions/create
// for more details.
type CompletionReq struct {

	// Model field is the ID of the model.
	// This is the required field.
	Model string `json:"model"`

	// Prompt generate completions for, encoded as a string,
	// array of strings, array of tokens, or array of token arrays.
	//
	// Note that <|endoftext|> is the document separator that the model
	// sees during training, so if a prompt is not specified the model
	// will generate as if from the beginning of a new document.
	//
	// This is a required field.
	Prompt PromptType `json:"prompt"`

	// BestOf Generates best_of completions server-side and returns the "best" (the one with the highest log probability per token). Results cannot be streamed.
	// When used with n, best_of controls the number of candidate completions and n specifies how many to return – best_of must be greater than n.
	//
	// Note: Because this parameter generates many completions, it can quickly consume your token quota. Use carefully and ensure that you have
	// reasonable settings for max_tokens and stop
	//
	// This is an optional field.
	BestOf int `json:"best_of,omitempty"`

	// Echo back the prompt in addition to the completion
	//
	// This is an optional field with default value false.
	Echo bool `json:"echo,omitempty"`

	// FrequencePenalty is the number between -2.0 and 2.0.
	// Positive values penalize new tokens based on their
	// existing frequency in the text so far, decreasing
	// the model's likelihood to repeat the same line verbatim.
	//
	// This is an optional field with default value 0
	FrequencyPenalty int `json:"frequency_penalty,omitempty"`

	// Modify the likelihood of specified tokens appearing in the completion.
	// Accepts a JSON object that maps tokens (specified by their token ID in
	// the GPT tokenizer) to an associated bias value from -100 to 100. You
	// can use this tokenizer tool to convert text to token IDs. Mathematically,
	// the bias is added to the logits generated by the model prior to sampling.
	// The exact effect will vary per model, but values between -1 and 1 should
	// decrease or increase likelihood of selection; values like -100 or 100 should
	// result in a ban or exclusive selection of the relevant token.
	//
	// As an example, you can pass {"50256": -100} to prevent the <|endoftext|> token
	// from being generated.
	//
	// This is an optional field with default value null
	LogitBias map[string]int `json:"logit_bias,omitempty"`

	// LogProbs include the log probabilities on the logprobs most likely output tokens,
	// as well the chosen tokens. For example, if logprobs is 5, the API will return a
	// list of the 5 most likely tokens. The API will always return the logprob of the
	// sampled token, so there may be up to logprobs+1 elements in the response.
	// The maximum value for logprobs is 5.
	//
	// This is an optional field with a default value 5
	LogProbs int `json:"logprobs,omitempty"`

	// MaxTokens is the maximum number of tokens that can be generated in the completion.
	// The token count of your prompt plus max_tokens cannot exceed the model's context
	// length. Example Python code for counting tokens.
	//
	// This is an optional field with default value 16
	MaxTokens int `json:"max_tokens,omitempty"`

	// N is how many completions to generate for each prompt.
	// Note: Because this parameter generates many completions,
	// it can quickly consume your token quota. Use carefully and
	// ensure that you have reasonable settings for max_tokens and stop.
	//
	// This is an optional field with default value 1
	N int `json:"n,omitempty"`

	// PresencePenalty is number between -2.0 and 2.0. Positive values
	// penalize new tokens based on whether they appear in the text so far,
	// increasing the model's likelihood to talk about new topics.
	// See more information about frequency and presence penalties.
	//
	// This is an optional field with default value 0
	PresencePenalty int `json:"presence_penalty,omitempty"`

	// Seed if specified, our system will make a best effort to sample
	// deterministically, such that repeated requests with the same seed
	// and parameters should return the same result.
	// Determinism is not guaranteed, and you should refer to the system_fingerprint
	// response parameter to monitor changes in the backend.
	//
	// This is an optional field with default value 0
	Seed int `json:"seed,omitempty"`

	// Up to 4 sequences where the API will stop generating
	// further tokens. The returned text will not contain the
	// stop sequence.
	//
	// This is an optional field with default value null
	Stop []string `json:"stop,omitempty"`

	// Stream  Whether to stream back partial progress.
	// If set, tokens will be sent as data-only server-sent
	// events as they become available, with the stream terminated
	// by a data: [DONE] message.
	//
	// This is an optional field with default value false
	Stream bool `json:"stream,omitempty"`

	// StreamOptions for streaming response. Only set this when you set stream: true.
	//
	// This is an optional field with default value to null
	StreamOptions any `json:"stream_options,omitempty"`

	// Suffix is the suffix that comes after a completion of inserted text.
	// This parameter is only supported for gpt-3.5-turbo-instruct.
	//
	// This is an optional value with default value null
	Suffix string `json:"suffix,omitempty"`

	// Temperature is the sampling temperature to use, between 0 and 2.
	// Higher values like 0.8 will make the output more random, while
	// lower values like 0.2 will make it more focused and deterministic.
	// We generally recommend altering this or top_p but not both.
	//
	// This is an optional field with default value 1.
	Temperature int `json:"temperature,omitempty"`

	// TopP is an alternative to sampling with temperature, called nucleus sampling,
	// where the model considers the results of the tokens with top_p probability mass.
	// So 0.1 means only the tokens comprising the top 10% probability mass are considered.
	// We generally recommend altering this or temperature but not both.
	//
	// This is an optional field with default value of 1
	TopP int `json:"top_p,omitempty"`

	// User is a unique identifier representing your end-user, which can help
	// OpenAI to monitor and detect abuse.
	//
	// This is an optional field
	User string `json:"user,omitempty"`
}

// MarshalJSON customizes the JSON encoding for the CompletionRequest struct.
// It ensures that the "prompt" field is serialized based on its kind:
// - If the kind is PromptKindString, the StringValue is used.
// - If the kind is PromptKindArray, the Array is used.
// - Otherwise, the ArrayOfTokens is used.
// This method wraps the CompletionRequest in an anonymous struct to include
// the transformed "prompt" field while preserving the original structure.
func (c *CompletionReq) MarshalJSON() ([]byte, error) {
	var prompt any
	switch c.Prompt.Kind {
	case PromptKindString:
		prompt = c.Prompt.StringValue
	case PromptKindStringArray:
		prompt = c.Prompt.StringArray
	case PromptKindTokenArray:
		prompt = c.Prompt.TokenArray
	case PromptKindArrayOfTokens:
		prompt = c.Prompt.ArrayOfTokens
	default:
		return nil, nil
	}

	type Alias CompletionReq
	return json.Marshal(&struct {
		*Alias
		Prompt any `json:"prompt"`
	}{
		Prompt: prompt,
		Alias:  (*Alias)(c),
	})
}

// CompletionLogProbsResp completion choices logprobs response
//
// The logprobs field types are not specified in the OpenAI API documentation,
// so I am using specifcations derived from ChatGPT
type CompletionLogProbsResp struct {
	TextOffset    []int                `json:"text_offset"`
	TokenLogProbs []float64            `json:"token_logprobs"`
	Tokens        []string             `json:"tokens"`
	TopLogProbs   []map[string]float64 `json:"top_logprobs"`
}

// CompletionChoicesResp completion choices response
type CompletionChoicesResp struct {
	Text         string                  `json:"text"`
	Index        int                     `json:"index"`
	LogProbs     *CompletionLogProbsResp `json:"logprobs,omitempty"`
	FinishReason string                  `json:"finish_reason"`
}

// CompletionUsageResp represents completion usage response
type CompletionUsageResp struct {
	PromptTokens     int `json:"prompt_tokens"`
	CompletionTokens int `json:"completion_tokens"`
	TotalTokens      int `json:"total_tokens"`
}

// CompletionResponse is an abstraction of completion response
//
// Refer to https://platform.openai.com/docs/api-reference/completions/object
type CompletionResponse struct {
	Choices           []CompletionChoicesResp `json:"choices"`
	Created           int                     `json:"created,omitempty"`
	ID                string                  `json:"id,omitempty"`
	Model             string                  `json:"model,omitempty"`
	Object            string                  `json:"object,omitempty"`
	SystemFingerPrint string                  `json:"system_fingerprint,omitempty"`
	Usage             CompletionUsageResp     `json:"usage,omitempty"`
}

func (o client) Completion(request *CompletionReq) ([]CompletionResponse, error) {
	endPoint, err := url.JoinPath(o.baseURL, "/v1/completions")
	if err != nil {
		return nil, err
	}

	reqBody := &bytes.Buffer{}
	if err := json.NewEncoder(reqBody).Encode(request); err != nil {
		return nil, err
	}
	req, err := http.NewRequest(http.MethodPost, endPoint, reqBody)
	if err != nil {
		return nil, err
	}

	req.Header.Set("Content-Type", "application/json")

	response, err := o.client.Do(req)
	if err != nil {
		return nil, err
	}
	defer func() {
		io.Copy(io.Discard, response.Body) // Ensure the body is fully read
		response.Body.Close()
	}()

	decoder := json.NewDecoder(response.Body)
	cResponses := make([]CompletionResponse, 0)
	for decoder.More() {
		var cResponse CompletionResponse
		if err := decoder.Decode(&cResponse); err != nil {
			return nil, err
		}
		cResponses = append(cResponses, cResponse)
	}
	return cResponses, nil
}
